export interface Tool {
  slug: string;
  name: string;
  category: string;
  description: string;
  pricing: "free" | "freemium" | "paid" | "open-source";
  score: number;
  pros: string[];
  cons: string[];
  url: string;
  tags: string[];
}

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  readTime: string;
  featured?: boolean;
}

export interface Category {
  slug: string;
  name: string;
  description: string;
  icon: string;
  count: number;
  color: string;
}

export const categories: Category[] = [
  { slug: "cicd", name: "CI/CD & Automation", description: "Sürekli entegrasyon ve dağıtım pipeline'ları, build otomasyonu ve release yönetimi.", icon: "git-branch", count: 8, color: "cyan" },
  { slug: "container", name: "Container & Orchestration", description: "Konteyner çalışma zamanları, orkestrasyon platformları ve servis mesh çözümleri.", icon: "layers", count: 7, color: "cyan" },
  { slug: "iac", name: "Infrastructure as Code", description: "Altyapı tanımlama, konfigürasyon yönetimi ve otomatik provizyon araçları.", icon: "server", count: 7, color: "cyan" },
  { slug: "monitoring", name: "Monitoring & Observability", description: "Metrik toplama, log yönetimi, distributed tracing ve alerting sistemleri.", icon: "activity", count: 8, color: "cyan" },
  { slug: "security", name: "Security & Compliance", description: "Güvenlik taraması, zafiyet tespiti, secret yönetimi ve uyumluluk kontrolleri.", icon: "shield", count: 7, color: "cyan" },
  { slug: "ai-ml", name: "AI & ML Tools", description: "Yapay zekâ API'leri, kod asistanları, ML pipeline yönetimi ve model servisi.", icon: "brain", count: 6, color: "cyan" },
  { slug: "cloud", name: "Cloud Platforms", description: "Büyük ölçekli bulut altyapıları, compute, storage ve managed servisler.", icon: "cloud", count: 5, color: "cyan" },
  { slug: "dev-tools", name: "Developer Tools", description: "Kod editörleri, IDE'ler, API test araçları ve geliştirici üretkenlik çözümleri.", icon: "code", count: 6, color: "cyan" },
  { slug: "database", name: "Database & Data", description: "İlişkisel ve NoSQL veritabanları, mesaj kuyrukları ve arama motorları.", icon: "database", count: 6, color: "cyan" },
  { slug: "collaboration", name: "Collaboration & Project", description: "Proje yönetimi, takım iletişimi, issue tracking ve dokümantasyon platformları.", icon: "users", count: 5, color: "cyan" },
];

export const tools: Tool[] = [
  // ─── CI/CD & Automation (8) ───
  {
    slug: "github-actions",
    name: "GitHub Actions",
    category: "cicd",
    description: "GitHub'a entegre CI/CD platformu. Repository içinden workflow tanımlayarak build, test ve deploy süreçlerini otomatikleştirir.",
    pricing: "freemium",
    score: 9.2,
    pros: ["GitHub ile doğal entegrasyon", "Geniş marketplace ve hazır action'lar", "Matrix build desteği", "Self-hosted runner seçeneği"],
    cons: ["Ücretsiz dakika limiti kısıtlı", "Karmaşık workflow'larda debug zorluğu", "GitHub dışı projelerde kullanışsız"],
    url: "https://github.com/features/actions",
    tags: ["CI/CD", "automation", "GitHub", "pipeline"],
  },
  {
    slug: "gitlab-cicd",
    name: "GitLab CI/CD",
    category: "cicd",
    description: "GitLab'ın yerleşik CI/CD çözümü. Tek platform üzerinden kaynak kod yönetimi, CI/CD, güvenlik taraması ve dağıtım sağlar.",
    pricing: "freemium",
    score: 9.0,
    pros: ["All-in-one DevOps platformu", "Auto DevOps özelliği", "Dahilî container registry", "Güçlü SAST/DAST entegrasyonu"],
    cons: ["Arayüz karmaşıklığı yüksek", "Self-managed kurulum kaynak tüketir", "Büyük instance'larda performans sorunları"],
    url: "https://about.gitlab.com/stages-devops-lifecycle/continuous-integration/",
    tags: ["CI/CD", "DevOps", "GitLab", "pipeline"],
  },
  {
    slug: "jenkins",
    name: "Jenkins",
    category: "cicd",
    description: "En yaygın açık kaynak otomasyon sunucusu. Binlerce eklenti ile her türlü build, test ve deploy senaryosunu destekler.",
    pricing: "open-source",
    score: 7.5,
    pros: ["Devasa eklenti ekosistemi", "Tam özelleştirme imkânı", "On-premise çalışabilir", "Büyük ve aktif topluluk"],
    cons: ["Eski arayüz ve kullanıcı deneyimi", "Bakım ve güncelleme yükü yüksek", "Groovy pipeline söz dizimi karmaşık"],
    url: "https://www.jenkins.io/",
    tags: ["CI/CD", "open-source", "automation", "pipeline"],
  },
  {
    slug: "circleci",
    name: "CircleCI",
    category: "cicd",
    description: "Bulut tabanlı CI/CD platformu. Hızlı build süreleri ve akıllı caching mekanizmasıyla öne çıkar.",
    pricing: "freemium",
    score: 8.3,
    pros: ["Hızlı build süreleri", "Docker layer caching desteği", "Paralel iş çalıştırma", "Orb ekosistemi ile yeniden kullanılabilir config"],
    cons: ["Ücretsiz planda sınırlı kredi", "Self-hosted seçenek pahalı", "Karmaşık monorepo desteği"],
    url: "https://circleci.com/",
    tags: ["CI/CD", "cloud", "automation", "pipeline"],
  },
  {
    slug: "travis-ci",
    name: "Travis CI",
    category: "cicd",
    description: "Açık kaynak projeler için popüler CI/CD servisi. Basit YAML konfigürasyonu ile hızlıca pipeline kurulumu sağlar.",
    pricing: "freemium",
    score: 7.2,
    pros: ["Kolay kurulum ve basit YAML yapılandırması", "Açık kaynak projeler için ücretsiz", "Çoklu dil ve platform desteği"],
    cons: ["Ücretsiz plan kısıtlamaları arttı", "Build süreleri rakiplerine göre yavaş", "Topluluk desteği azaldı"],
    url: "https://www.travis-ci.com/",
    tags: ["CI/CD", "open-source", "automation"],
  },
  {
    slug: "azure-devops-pipelines",
    name: "Azure DevOps Pipelines",
    category: "cicd",
    description: "Microsoft'un bulut tabanlı CI/CD çözümü. Azure ekosistemiyle derin entegrasyon ve hibrit pipeline desteği sunar.",
    pricing: "freemium",
    score: 8.5,
    pros: ["Azure servisleriyle doğal entegrasyon", "Paralel iş desteği güçlü", "YAML ve klasik editör seçeneği", "Kapsamlı artifact yönetimi"],
    cons: ["Azure dışı ortamlarda avantajı azalır", "Arayüz öğrenme eğrisi yüksek", "Dokümantasyon dağınık"],
    url: "https://azure.microsoft.com/en-us/products/devops/pipelines",
    tags: ["CI/CD", "Azure", "Microsoft", "pipeline"],
  },
  {
    slug: "tekton",
    name: "Tekton",
    category: "cicd",
    description: "Kubernetes-native CI/CD framework'ü. Cloud-native pipeline'ları Kubernetes kaynak tanımları olarak oluşturmayı sağlar.",
    pricing: "open-source",
    score: 7.8,
    pros: ["Kubernetes-native tasarım", "Taşınabilir ve standartlara uygun", "Modüler pipeline bileşenleri", "Vendor-agnostic yapı"],
    cons: ["Öğrenme eğrisi dik", "Kubernetes bilgisi zorunlu", "Ekosistem henüz olgunlaşmadı"],
    url: "https://tekton.dev/",
    tags: ["CI/CD", "Kubernetes", "cloud-native", "pipeline"],
  },
  {
    slug: "drone-ci",
    name: "Drone CI",
    category: "cicd",
    description: "Container-native CI/CD platformu. Her pipeline adımı izole bir konteyner içinde çalışır, basit YAML konfigürasyonu kullanır.",
    pricing: "open-source",
    score: 7.6,
    pros: ["Container-first yaklaşım", "Basit ve okunabilir YAML yapılandırması", "Hafif ve hızlı kurulum", "Eklenti sistemi Docker image tabanlı"],
    cons: ["Topluluk Jenkins kadar büyük değil", "Kurumsal destek sınırlı", "Karmaşık workflow'lar için yetersiz kalabilir"],
    url: "https://www.drone.io/",
    tags: ["CI/CD", "container", "automation", "open-source"],
  },

  // ─── Container & Orchestration (7) ───
  {
    slug: "docker",
    name: "Docker",
    category: "container",
    description: "Endüstri standardı konteyner platformu. Uygulamaları bağımlılıklarıyla birlikte paketleyerek her ortamda tutarlı çalışmayı garanti eder.",
    pricing: "freemium",
    score: 9.4,
    pros: ["Endüstri standardı konteyner formatı", "Devasa image ekosistemi (Docker Hub)", "Kolay öğrenme eğrisi", "Çoklu platform desteği"],
    cons: ["Docker Desktop lisans ücreti (büyük şirketler)", "Güvenlik için root erişimi gerektirir", "Image boyutları büyüyebilir"],
    url: "https://www.docker.com/",
    tags: ["container", "virtualization", "DevOps", "microservices"],
  },
  {
    slug: "kubernetes",
    name: "Kubernetes",
    category: "container",
    description: "Konteyner orkestrasyon standardı. Otomatik ölçeklendirme, self-healing, rolling update ve servis keşfi sağlar.",
    pricing: "open-source",
    score: 9.3,
    pros: ["Otomatik ölçeklendirme ve self-healing", "Geniş ekosistem ve topluluk", "Tüm bulut sağlayıcılarında managed seçenek", "Deklaratif konfigürasyon"],
    cons: ["Öğrenme eğrisi çok dik", "Küçük projeler için aşırı karmaşık", "Operasyonel yük yüksek"],
    url: "https://kubernetes.io/",
    tags: ["orchestration", "container", "cloud-native", "scaling"],
  },
  {
    slug: "podman",
    name: "Podman",
    category: "container",
    description: "Daemonless konteyner motoru. Root yetkisi gerektirmeden konteyner çalıştırır, Docker CLI ile uyumlu komut yapısı sunar.",
    pricing: "open-source",
    score: 8.0,
    pros: ["Rootless konteyner çalıştırma", "Daemon gerektirmez", "Docker CLI uyumluluğu", "Pod kavramı ile Kubernetes benzeri yapı"],
    cons: ["Docker Compose desteği tam değil", "Ekosistem Docker kadar geniş değil", "Bazı araçlarla uyumluluk sorunları"],
    url: "https://podman.io/",
    tags: ["container", "rootless", "security", "open-source"],
  },
  {
    slug: "rancher",
    name: "Rancher",
    category: "container",
    description: "Çoklu Kubernetes cluster yönetim platformu. Farklı ortamlardaki cluster'ları tek bir arayüzden yönetmeyi sağlar.",
    pricing: "open-source",
    score: 8.2,
    pros: ["Çoklu cluster yönetimi", "Kullanıcı dostu web arayüzü", "RKE ile kolay Kubernetes kurulumu", "Kapsamlı RBAC yönetimi"],
    cons: ["Büyük ölçekte performans sorunları", "SUSE satın alımı sonrası belirsizlikler", "Ek kaynak tüketimi"],
    url: "https://www.rancher.com/",
    tags: ["Kubernetes", "management", "multi-cluster", "orchestration"],
  },
  {
    slug: "helm",
    name: "Helm",
    category: "container",
    description: "Kubernetes paket yöneticisi. Chart'lar aracılığıyla karmaşık uygulamaları tek komutla kurmayı ve yönetmeyi sağlar.",
    pricing: "open-source",
    score: 8.5,
    pros: ["Kubernetes uygulama paketleme standardı", "Zengin chart repository ekosistemi", "Sürüm yönetimi ve rollback", "Template desteği ile tekrar kullanılabilirlik"],
    cons: ["Template söz dizimi karmaşık olabilir", "Chart bağımlılık yönetimi zor", "Güvenlik açıkları chart kaynaklı olabilir"],
    url: "https://helm.sh/",
    tags: ["Kubernetes", "package-manager", "deployment", "charts"],
  },
  {
    slug: "istio",
    name: "Istio",
    category: "container",
    description: "Kubernetes için servis mesh çözümü. Servisler arası trafik yönetimi, güvenlik politikaları ve observability sağlar.",
    pricing: "open-source",
    score: 7.9,
    pros: ["Kapsamlı trafik yönetimi", "mTLS ile servisler arası şifreleme", "Detaylı observability metrikleri", "Canary ve blue-green deployment desteği"],
    cons: ["Kaynak tüketimi yüksek", "Konfigürasyon karmaşıklığı fazla", "Performans overhead'i var"],
    url: "https://istio.io/",
    tags: ["service-mesh", "Kubernetes", "networking", "security"],
  },
  {
    slug: "openshift",
    name: "OpenShift",
    category: "container",
    description: "Red Hat'in kurumsal Kubernetes platformu. Güvenlik, CI/CD ve geliştirici araçlarını entegre bir şekilde sunar.",
    pricing: "paid",
    score: 8.1,
    pros: ["Kurumsal düzeyde güvenlik ve destek", "Dahilî CI/CD ve image registry", "Geliştirici dostu web konsolu", "Red Hat ekosistemi entegrasyonu"],
    cons: ["Lisans maliyeti yüksek", "Standart Kubernetes'ten sapmalar var", "Kaynak gereksinimleri fazla"],
    url: "https://www.redhat.com/en/technologies/cloud-computing/openshift",
    tags: ["Kubernetes", "enterprise", "PaaS", "Red Hat"],
  },

  // ─── Infrastructure as Code (7) ───
  {
    slug: "terraform",
    name: "Terraform",
    category: "iac",
    description: "HashiCorp'un IaC aracı. HCL diliyle çoklu bulut sağlayıcıda altyapı tanımlama ve yönetimi sağlar.",
    pricing: "open-source",
    score: 9.1,
    pros: ["Çoklu bulut sağlayıcı desteği", "Geniş provider ekosistemi", "Plan/Apply ile güvenli değişiklik", "State yönetimi ile drift tespiti"],
    cons: ["HCL öğrenme eğrisi", "State dosyası yönetimi dikkat gerektirir", "HashiCorp lisans değişikliği tartışmaları"],
    url: "https://www.terraform.io/",
    tags: ["IaC", "multi-cloud", "provisioning", "HCL"],
  },
  {
    slug: "pulumi",
    name: "Pulumi",
    category: "iac",
    description: "Genel amaçlı programlama dilleriyle altyapı tanımlama platformu. TypeScript, Python, Go gibi dillerle IaC yazmayı sağlar.",
    pricing: "freemium",
    score: 8.4,
    pros: ["Bilinen programlama dilleriyle IaC", "Güçlü tip kontrolü ve IDE desteği", "Test yazılabilir altyapı kodu", "Terraform provider'larını kullanabilir"],
    cons: ["Topluluk Terraform kadar büyük değil", "Programlama bilgisi gerektiri", "State yönetimi için Pulumi Cloud öneriliyor"],
    url: "https://www.pulumi.com/",
    tags: ["IaC", "multi-cloud", "TypeScript", "Python"],
  },
  {
    slug: "ansible",
    name: "Ansible",
    category: "iac",
    description: "Agentless konfigürasyon yönetim aracı. YAML tabanlı playbook'larla sunucu yapılandırması ve uygulama dağıtımı yapar.",
    pricing: "open-source",
    score: 8.7,
    pros: ["Agentless mimari, SSH üzerinden çalışır", "Basit YAML söz dizimi", "Geniş modül koleksiyonu", "Red Hat desteği ve Ansible Galaxy"],
    cons: ["Büyük ölçekte performans sorunları", "Karmaşık state yönetimi yok", "Windows desteği Linux kadar güçlü değil"],
    url: "https://www.ansible.com/",
    tags: ["configuration-management", "automation", "YAML", "agentless"],
  },
  {
    slug: "cloudformation",
    name: "AWS CloudFormation",
    category: "iac",
    description: "AWS'in yerel IaC servisi. JSON veya YAML şablonlarıyla AWS kaynaklarını deklaratif olarak tanımlar ve yönetir.",
    pricing: "free",
    score: 7.8,
    pros: ["AWS ile doğal entegrasyon", "Ücretsiz kullanım", "Stack yönetimi ve drift detection", "Kapsamlı AWS kaynak desteği"],
    cons: ["Sadece AWS ile çalışır", "YAML/JSON şablonları uzun ve karmaşık", "Hata mesajları yetersiz", "Değişiklik süreleri yavaş olabilir"],
    url: "https://aws.amazon.com/cloudformation/",
    tags: ["IaC", "AWS", "provisioning", "cloud"],
  },
  {
    slug: "opentofu",
    name: "OpenTofu",
    category: "iac",
    description: "Terraform'un açık kaynak fork'u. BSL lisans değişikliği sonrası Linux Foundation altında geliştirilen topluluk odaklı IaC aracı.",
    pricing: "open-source",
    score: 8.0,
    pros: ["Gerçek açık kaynak lisans (MPL 2.0)", "Terraform ile yüksek uyumluluk", "Linux Foundation desteği", "State encryption desteği"],
    cons: ["Terraform'dan ayrışma riski", "Ekosistem henüz tam olgunlaşmadı", "Bazı kurumsal özellikler eksik"],
    url: "https://opentofu.org/",
    tags: ["IaC", "open-source", "multi-cloud", "provisioning"],
  },
  {
    slug: "crossplane",
    name: "Crossplane",
    category: "iac",
    description: "Kubernetes-native altyapı yönetim platformu. Kubernetes API'si üzerinden bulut kaynaklarını yönetmeyi sağlar.",
    pricing: "open-source",
    score: 7.7,
    pros: ["Kubernetes-native yaklaşım", "GitOps ile uyumlu", "Çoklu bulut desteği", "Composition ile soyutlama katmanı"],
    cons: ["Kubernetes bilgisi zorunlu", "Olgunluk seviyesi gelişiyor", "Provider desteği Terraform kadar geniş değil"],
    url: "https://www.crossplane.io/",
    tags: ["IaC", "Kubernetes", "multi-cloud", "cloud-native"],
  },
  {
    slug: "chef",
    name: "Chef",
    category: "iac",
    description: "Ruby tabanlı konfigürasyon yönetim aracı. Cookbook ve recipe kavramlarıyla sunucu konfigürasyonunu kod olarak tanımlar.",
    pricing: "freemium",
    score: 7.1,
    pros: ["Güçlü ve esnek Ruby DSL", "InSpec ile compliance testing", "Büyük kurumsal müşteri tabanı"],
    cons: ["Ruby bilgisi gerektirir", "Ansible'a göre daha karmaşık", "Topluluk ilgisi azaldı", "Agent kurulumu gerektirir"],
    url: "https://www.chef.io/",
    tags: ["configuration-management", "Ruby", "compliance", "automation"],
  },

  // ─── Monitoring & Observability (8) ───
  {
    slug: "prometheus",
    name: "Prometheus",
    category: "monitoring",
    description: "Açık kaynak metrik toplama ve alerting sistemi. Pull-based model ile zaman serisi verileri toplar, PromQL sorgu diliyle analiz sağlar.",
    pricing: "open-source",
    score: 9.2,
    pros: ["Güçlü PromQL sorgu dili", "Kubernetes ile mükemmel entegrasyon", "Pull-based mimari", "Geniş exporter ekosistemi"],
    cons: ["Uzun süreli veri saklama için ek çözüm gerekir", "Yüksek kardinalite sorunları", "Dahilî dashboard yok"],
    url: "https://prometheus.io/",
    tags: ["monitoring", "metrics", "alerting", "time-series"],
  },
  {
    slug: "grafana",
    name: "Grafana",
    category: "monitoring",
    description: "Açık kaynak görselleştirme ve dashboard platformu. Çoklu veri kaynağından veri çekerek interaktif panolar oluşturur.",
    pricing: "open-source",
    score: 9.3,
    pros: ["Çoklu veri kaynağı desteği", "Zengin görselleştirme seçenekleri", "Aktif topluluk ve dashboard paylaşımı", "Alerting ve notification desteği"],
    cons: ["Karmaşık dashboard'lar performansı etkiler", "Yetkilendirme yönetimi sınırlı", "Bazı özellikler Enterprise sürümüne özel"],
    url: "https://grafana.com/",
    tags: ["visualization", "dashboard", "monitoring", "observability"],
  },
  {
    slug: "datadog",
    name: "Datadog",
    category: "monitoring",
    description: "Bulut ölçekli monitoring ve analytics platformu. Metrikler, loglar, trace'ler ve güvenlik verilerini tek bir platformda birleştirir.",
    pricing: "paid",
    score: 9.0,
    pros: ["All-in-one observability platformu", "700+ entegrasyon", "Güçlü APM ve distributed tracing", "Yapay zekâ destekli anomali tespiti"],
    cons: ["Maliyet çok hızlı yükselebilir", "Veri çıkışı (egress) pahalı", "Vendor lock-in riski yüksek"],
    url: "https://www.datadoghq.com/",
    tags: ["monitoring", "APM", "logging", "cloud"],
  },
  {
    slug: "new-relic",
    name: "New Relic",
    category: "monitoring",
    description: "Full-stack observability platformu. APM, altyapı izleme, log yönetimi ve browser monitoring hizmetlerini sunar.",
    pricing: "freemium",
    score: 8.5,
    pros: ["Cömert ücretsiz plan (100 GB/ay)", "Kapsamlı APM yetenekleri", "Kullanıcı dostu arayüz", "NRQL sorgu dili güçlü"],
    cons: ["Fiyatlandırma karmaşık", "Agent performans overhead'i", "Bazı özellikler Pro plan gerektirir"],
    url: "https://newrelic.com/",
    tags: ["APM", "monitoring", "observability", "full-stack"],
  },
  {
    slug: "zabbix",
    name: "Zabbix",
    category: "monitoring",
    description: "Kurumsal düzeyde açık kaynak izleme çözümü. Ağ, sunucu, bulut ve uygulama izleme ile kapsamlı alerting sağlar.",
    pricing: "open-source",
    score: 7.8,
    pros: ["Tamamen ücretsiz ve açık kaynak", "Kapsamlı ağ ve altyapı izleme", "Esnek template sistemi", "Auto-discovery özelliği"],
    cons: ["Arayüzü eski ve karmaşık", "İlk kurulum ve yapılandırma zaman alır", "Modern cloud-native ortamlara adaptasyonu zor"],
    url: "https://www.zabbix.com/",
    tags: ["monitoring", "network", "alerting", "enterprise"],
  },
  {
    slug: "elastic-stack",
    name: "Elastic Stack",
    category: "monitoring",
    description: "Elasticsearch, Logstash ve Kibana üçlüsü. Log toplama, arama, analiz ve görselleştirme için endüstri standardı çözüm.",
    pricing: "freemium",
    score: 8.6,
    pros: ["Güçlü full-text arama motoru", "Kapsamlı log analizi", "Kibana ile zengin görselleştirme", "Geniş topluluk ve entegrasyon"],
    cons: ["Kaynak tüketimi çok yüksek (RAM)", "Cluster yönetimi karmaşık", "Lisans değişiklikleri (SSPL) tartışmalı"],
    url: "https://www.elastic.co/elastic-stack",
    tags: ["logging", "search", "analytics", "observability"],
  },
  {
    slug: "grafana-loki",
    name: "Grafana Loki",
    category: "monitoring",
    description: "Grafana Labs'ın log toplama sistemi. Prometheus'tan esinlenen etiket bazlı yaklaşımla logları indekslemeden verimli şekilde saklar.",
    pricing: "open-source",
    score: 8.2,
    pros: ["Düşük kaynak tüketimi", "Prometheus etiket modeli ile uyumlu", "Grafana ile doğal entegrasyon", "Maliyet etkin log saklama"],
    cons: ["Full-text arama yeteneği sınırlı", "Karmaşık sorgularda Elasticsearch'e göre yavaş", "Olgunluk seviyesi Elasticsearch'ün gerisinde"],
    url: "https://grafana.com/oss/loki/",
    tags: ["logging", "Grafana", "observability", "cloud-native"],
  },
  {
    slug: "jaeger",
    name: "Jaeger",
    category: "monitoring",
    description: "Açık kaynak distributed tracing platformu. Mikroservis mimarilerinde istek akışını izleyerek performans darboğazlarını tespit eder.",
    pricing: "open-source",
    score: 8.0,
    pros: ["OpenTelemetry uyumlu", "Kubernetes-native dağıtım", "Servis bağımlılık haritası", "Adaptif örnekleme"],
    cons: ["Sadece tracing odaklı", "Depolama backend seçimi karmaşık", "UI yetenekleri sınırlı"],
    url: "https://www.jaegertracing.io/",
    tags: ["tracing", "microservices", "observability", "OpenTelemetry"],
  },

  // ─── Security & Compliance (7) ───
  {
    slug: "trivy",
    name: "Trivy",
    category: "security",
    description: "Aqua Security'nin kapsamlı güvenlik tarayıcısı. Container image, dosya sistemi, Git repository ve Kubernetes yapılandırmalarını tarar.",
    pricing: "open-source",
    score: 8.8,
    pros: ["Hızlı ve kapsamlı tarama", "Container, IaC ve SBOM desteği", "CI/CD entegrasyonu kolay", "Sıfır konfigürasyon ile çalışır"],
    cons: ["False positive oranı yüksek olabilir", "Özel registry desteği yapılandırma gerektirir", "Raporlama seçenekleri sınırlı"],
    url: "https://trivy.dev/",
    tags: ["security", "container", "vulnerability", "scanning"],
  },
  {
    slug: "snyk",
    name: "Snyk",
    category: "security",
    description: "Geliştirici odaklı güvenlik platformu. Açık kaynak bağımlılıkları, konteyner imajları ve IaC kodlarındaki güvenlik açıklarını tespit eder.",
    pricing: "freemium",
    score: 8.6,
    pros: ["Geliştirici dostu arayüz", "Otomatik düzeltme önerileri", "Geniş dil ve framework desteği", "IDE ve CI/CD entegrasyonu"],
    cons: ["Ücretsiz plan sınırlı test hakkı", "Enterprise fiyatlandırma yüksek", "Bazı dillerde false positive fazla"],
    url: "https://snyk.io/",
    tags: ["security", "dependency", "vulnerability", "DevSecOps"],
  },
  {
    slug: "hashicorp-vault",
    name: "HashiCorp Vault",
    category: "security",
    description: "Secret yönetim ve veri şifreleme platformu. API anahtarları, şifreler ve sertifikaları merkezi olarak yönetir ve denetler.",
    pricing: "freemium",
    score: 9.0,
    pros: ["Kapsamlı secret yönetimi", "Dinamik secret oluşturma", "Çoklu auth backend desteği", "Audit logging ve politika yönetimi"],
    cons: ["Kurulum ve operasyonel karmaşıklık", "Yüksek erişilebilirlik yapılandırması zor", "Lisans değişikliği (BSL) endişeleri"],
    url: "https://www.vaultproject.io/",
    tags: ["secrets", "encryption", "security", "compliance"],
  },
  {
    slug: "falco",
    name: "Falco",
    category: "security",
    description: "Kubernetes ve konteyner runtime güvenlik aracı. Sistem çağrılarını izleyerek şüpheli aktiviteleri gerçek zamanlı tespit eder.",
    pricing: "open-source",
    score: 8.1,
    pros: ["Runtime tehdit tespiti", "Kubernetes-native entegrasyon", "Esnek kural motoru", "CNCF graduated projesi"],
    cons: ["Kernel modülü/eBPF gereksinimi", "Kural yazımı uzmanlık gerektirir", "Yüksek trafikli ortamlarda performans etkisi"],
    url: "https://falco.org/",
    tags: ["runtime-security", "Kubernetes", "threat-detection", "CNCF"],
  },
  {
    slug: "checkov",
    name: "Checkov",
    category: "security",
    description: "IaC güvenlik tarayıcısı. Terraform, CloudFormation, Kubernetes ve Dockerfile yapılandırmalarında güvenlik ihlallerini tespit eder.",
    pricing: "open-source",
    score: 8.3,
    pros: ["1000+ dahilî güvenlik politikası", "Çoklu IaC framework desteği", "CI/CD pipeline entegrasyonu", "Özel politika yazma desteği"],
    cons: ["Tarama süresi büyük projelerde uzayabilir", "False positive ayarlaması gerektirir", "Bazı provider'lar için kural kapsamı sınırlı"],
    url: "https://www.checkov.io/",
    tags: ["IaC", "security", "compliance", "policy-as-code"],
  },
  {
    slug: "sonarqube",
    name: "SonarQube",
    category: "security",
    description: "Kod kalitesi ve güvenlik analiz platformu. Statik kod analizi ile bug, güvenlik açığı ve code smell tespiti yapar.",
    pricing: "freemium",
    score: 8.4,
    pros: ["30+ dil desteği", "Kapsamlı kod kalitesi metrikleri", "Quality gate mekanizması", "CI/CD entegrasyonu kolay"],
    cons: ["Community Edition'da sınırlı dil desteği", "Büyük projelerde analiz süresi uzun", "Kurumsal özellikler pahalı"],
    url: "https://www.sonarsource.com/products/sonarqube/",
    tags: ["code-quality", "SAST", "security", "DevSecOps"],
  },
  {
    slug: "owasp-zap",
    name: "OWASP ZAP",
    category: "security",
    description: "Açık kaynak web uygulama güvenlik tarayıcısı. Otomatik ve manuel testlerle web uygulamalarındaki güvenlik açıklarını bulur.",
    pricing: "open-source",
    score: 7.9,
    pros: ["Tamamen ücretsiz ve açık kaynak", "Kapsamlı DAST yetenekleri", "Aktif ve pasif tarama modları", "CI/CD pipeline entegrasyonu"],
    cons: ["Arayüzü karmaşık", "False positive oranı yüksek", "Modern SPA uygulamalarında sınırlı kapsam"],
    url: "https://www.zaproxy.org/",
    tags: ["DAST", "web-security", "penetration-testing", "OWASP"],
  },

  // ─── AI & ML Tools (6) ───
  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    category: "ai-ml",
    description: "Yapay zekâ destekli kod asistanı. Kodlama sırasında bağlama uygun öneriler sunarak geliştirici üretkenliğini artırır.",
    pricing: "paid",
    score: 9.0,
    pros: ["IDE ile derin entegrasyon", "Çoklu dil ve framework desteği", "Chat modu ile kod açıklama", "Workspace anlama yeteneği"],
    cons: ["Aylık abonelik ücreti", "Bazen yanlış veya güvensiz kod önerir", "İnternet bağlantısı gerektirir", "Lisans endişeleri (açık kaynak kod)"],
    url: "https://github.com/features/copilot",
    tags: ["AI", "code-assistant", "productivity", "GitHub"],
  },
  {
    slug: "cursor",
    name: "Cursor",
    category: "ai-ml",
    description: "AI-first kod editörü. VS Code tabanlı olup yapay zekâ ile kod yazma, düzenleme ve anlama süreçlerini hızlandırır.",
    pricing: "freemium",
    score: 8.8,
    pros: ["AI-native editör deneyimi", "Codebase anlama ve bağlam yönetimi", "Çoklu model desteği", "VS Code eklenti uyumluluğu"],
    cons: ["Aylık abonelik maliyeti", "Büyük projelerde indeksleme yavaş", "VS Code'a bağımlılık"],
    url: "https://www.cursor.com/",
    tags: ["AI", "IDE", "code-editor", "productivity"],
  },
  {
    slug: "openai-api",
    name: "OpenAI API",
    category: "ai-ml",
    description: "GPT ve diğer OpenAI modellerine erişim sağlayan API platformu. Metin üretimi, analiz, görüntü ve ses işleme yetenekleri sunar.",
    pricing: "paid",
    score: 9.2,
    pros: ["En güçlü dil modelleri", "Kapsamlı API dokümantasyonu", "Function calling ve JSON mode", "Geniş SDK ve kütüphane desteği"],
    cons: ["Token bazlı fiyatlandırma maliyetli olabilir", "Rate limit kısıtlamaları", "Veri gizliliği endişeleri"],
    url: "https://platform.openai.com/",
    tags: ["AI", "LLM", "API", "GPT"],
  },
  {
    slug: "hugging-face",
    name: "Hugging Face",
    category: "ai-ml",
    description: "Açık kaynak ML model ve dataset platformu. Binlerce hazır model, dataset ve Spaces ile ML projelerini hızlandırır.",
    pricing: "freemium",
    score: 8.9,
    pros: ["Devasa açık kaynak model hub'ı", "Transformers kütüphanesi", "Spaces ile kolay demo dağıtımı", "Aktif araştırma topluluğu"],
    cons: ["Inference API limitleri", "Büyük modeller için yüksek compute gereksinimi", "Model kalitesi değişkenlik gösterir"],
    url: "https://huggingface.co/",
    tags: ["ML", "open-source", "models", "NLP"],
  },
  {
    slug: "mlflow",
    name: "MLflow",
    category: "ai-ml",
    description: "Açık kaynak ML yaşam döngüsü yönetim platformu. Deney takibi, model versiyonlama, dağıtım ve kayıt defteri sağlar.",
    pricing: "open-source",
    score: 8.2,
    pros: ["Deney takibi ve karşılaştırma", "Model registry ve versiyonlama", "Çoklu ML framework desteği", "Databricks entegrasyonu"],
    cons: ["Ölçeklendirme için ek altyapı gerekir", "UI yetenekleri sınırlı", "Gerçek zamanlı izleme eksik"],
    url: "https://mlflow.org/",
    tags: ["MLOps", "experiment-tracking", "model-registry", "open-source"],
  },
  {
    slug: "langchain",
    name: "LangChain",
    category: "ai-ml",
    description: "LLM tabanlı uygulama geliştirme framework'ü. Zincir, agent ve RAG kalıplarıyla AI uygulamalarını hızla oluşturmayı sağlar.",
    pricing: "open-source",
    score: 8.3,
    pros: ["Kapsamlı LLM entegrasyon desteği", "RAG ve agent framework'ü", "LangSmith ile observability", "Aktif geliştirme ve topluluk"],
    cons: ["API değişiklikleri sık yaşanır", "Soyutlama katmanı overhead yaratabilir", "Dokümantasyon geride kalabiliyor"],
    url: "https://www.langchain.com/",
    tags: ["LLM", "framework", "RAG", "agents"],
  },

  // ─── Cloud Platforms (5) ───
  {
    slug: "aws",
    name: "Amazon Web Services",
    category: "cloud",
    description: "Dünyanın en büyük bulut platformu. 200'den fazla servisle compute, storage, veritabanı, AI ve IoT çözümleri sunar.",
    pricing: "paid",
    score: 9.5,
    pros: ["En geniş servis yelpazesi", "Global altyapı ve edge noktaları", "Olgun ekosistem ve topluluk", "Kapsamlı sertifikasyon programı"],
    cons: ["Fiyatlandırma karmaşık", "Maliyet kontrolü zor", "Vendor lock-in riski yüksek"],
    url: "https://aws.amazon.com/",
    tags: ["cloud", "compute", "storage", "enterprise"],
  },
  {
    slug: "google-cloud",
    name: "Google Cloud Platform",
    category: "cloud",
    description: "Google'ın bulut platformu. BigQuery, GKE ve Vertex AI gibi servislerle veri analitiği ve AI alanında güçlü çözümler sunar.",
    pricing: "paid",
    score: 8.8,
    pros: ["Veri analitiği ve AI servisleri üstün", "GKE en iyi managed Kubernetes", "Global ağ altyapısı güçlü", "BigQuery benzersiz analitik gücü"],
    cons: ["Servis çeşitliliği AWS'e göre az", "Kurumsal destek algısı zayıf", "Konsol kullanıcı deneyimi tutarsız"],
    url: "https://cloud.google.com/",
    tags: ["cloud", "AI", "data-analytics", "Kubernetes"],
  },
  {
    slug: "azure",
    name: "Microsoft Azure",
    category: "cloud",
    description: "Microsoft'un bulut platformu. Hibrit bulut, kurumsal entegrasyon ve Active Directory ile Windows ekosistemiyle uyumlu çözümler sunar.",
    pricing: "paid",
    score: 9.0,
    pros: ["Microsoft ekosistemiyle derin entegrasyon", "Hibrit bulut çözümleri güçlü", "Kurumsal müşteri desteği", "Active Directory ve Office 365 entegrasyonu"],
    cons: ["Portal arayüzü yavaş ve karmaşık", "Servis isimlendirmesi kafa karıştırıcı", "Bazı servislerde stabilite sorunları"],
    url: "https://azure.microsoft.com/",
    tags: ["cloud", "hybrid", "enterprise", "Microsoft"],
  },
  {
    slug: "digitalocean",
    name: "DigitalOcean",
    category: "cloud",
    description: "Geliştirici odaklı bulut platformu. Basit fiyatlandırma, kolay kullanım ve hızlı kurulum ile küçük-orta ölçekli projeler için idealdir.",
    pricing: "paid",
    score: 8.0,
    pros: ["Basit ve şeffaf fiyatlandırma", "Geliştirici dostu arayüz", "Hızlı droplet oluşturma", "Kapsamlı dokümantasyon ve rehberler"],
    cons: ["Servis çeşitliliği sınırlı", "Kurumsal özellikler yetersiz", "Global bölge sayısı az"],
    url: "https://www.digitalocean.com/",
    tags: ["cloud", "developer", "simple", "VPS"],
  },
  {
    slug: "hetzner-cloud",
    name: "Hetzner Cloud",
    category: "cloud",
    description: "Avrupa merkezli uygun maliyetli bulut platformu. Güçlü fiyat/performans oranıyla özellikle Avrupa projelerinde tercih edilir.",
    pricing: "paid",
    score: 8.2,
    pros: ["Çok uygun fiyatlandırma", "Güçlü fiyat/performans oranı", "GDPR uyumlu Avrupa veri merkezleri", "Basit ve temiz API"],
    cons: ["Managed servisler sınırlı", "Global kapsama alanı dar", "Destek seçenekleri az"],
    url: "https://www.hetzner.com/cloud",
    tags: ["cloud", "Europe", "affordable", "VPS"],
  },

  // ─── Developer Tools (6) ───
  {
    slug: "vscode",
    name: "Visual Studio Code",
    category: "dev-tools",
    description: "Microsoft'un açık kaynak kod editörü. Zengin eklenti ekosistemi, dahilî terminal ve Git entegrasyonu ile en popüler editör.",
    pricing: "free",
    score: 9.4,
    pros: ["Devasa eklenti marketplace", "Hafif ve hızlı başlangıç", "Dahilî terminal ve Git desteği", "Remote development yetenekleri"],
    cons: ["Çok eklenti ile yavaşlayabilir", "Büyük projelerde RAM tüketimi", "Telemetri ve gizlilik endişeleri"],
    url: "https://code.visualstudio.com/",
    tags: ["editor", "IDE", "Microsoft", "extensions"],
  },
  {
    slug: "jetbrains-ides",
    name: "JetBrains IDEs",
    category: "dev-tools",
    description: "IntelliJ IDEA, WebStorm, PyCharm gibi profesyonel IDE ailesi. Derin kod analizi ve akıllı refactoring yetenekleri sunar.",
    pricing: "paid",
    score: 9.0,
    pros: ["Üstün kod analizi ve refactoring", "Dahilî veritabanı araçları", "Dile özel optimizasyonlar", "Güçlü debugger"],
    cons: ["Yıllık lisans ücreti yüksek", "Yüksek RAM ve CPU tüketimi", "Başlangıç süresi yavaş"],
    url: "https://www.jetbrains.com/",
    tags: ["IDE", "Java", "Python", "professional"],
  },
  {
    slug: "postman",
    name: "Postman",
    category: "dev-tools",
    description: "API geliştirme ve test platformu. API istekleri oluşturma, otomatik test yazma ve dokümantasyon üretme sağlar.",
    pricing: "freemium",
    score: 8.5,
    pros: ["Kullanıcı dostu arayüz", "Otomatik API test koleksiyonları", "Takım iş birliği özellikleri", "Mock server ve environment desteği"],
    cons: ["Ücretsiz planda sınırlı iş birliği", "Masaüstü uygulaması ağır", "Alternatiflerine göre yavaşlayabiliyor"],
    url: "https://www.postman.com/",
    tags: ["API", "testing", "documentation", "collaboration"],
  },
  {
    slug: "swagger-openapi",
    name: "Swagger / OpenAPI",
    category: "dev-tools",
    description: "API tasarım ve dokümantasyon standardı. OpenAPI spesifikasyonu ile API'leri tanımlama, test etme ve dokümante etme sağlar.",
    pricing: "free",
    score: 8.3,
    pros: ["Endüstri standardı API spesifikasyonu", "Otomatik kod ve dokümantasyon üretimi", "İnteraktif API keşif arayüzü", "Geniş araç ekosistemi"],
    cons: ["Büyük API'larda spec dosyası karmaşıklaşır", "Versiyonlama yönetimi zor", "Bazı ileri düzey senaryolar desteklenmiyor"],
    url: "https://swagger.io/",
    tags: ["API", "documentation", "specification", "REST"],
  },
  {
    slug: "gitkraken",
    name: "GitKraken",
    category: "dev-tools",
    description: "Görsel Git istemcisi. Karmaşık branch yapılarını görselleştirerek Git işlemlerini sezgisel hâle getirir.",
    pricing: "freemium",
    score: 7.8,
    pros: ["Görsel branch ve commit grafiği", "Sezgisel drag-and-drop işlemleri", "Dahilî merge conflict çözücü", "Jira ve GitHub entegrasyonu"],
    cons: ["Özel repolar için ücretli", "Büyük repolarda performans düşer", "Terminal kullanıcıları için gereksiz"],
    url: "https://www.gitkraken.com/",
    tags: ["Git", "GUI", "version-control", "productivity"],
  },
  {
    slug: "notion",
    name: "Notion",
    category: "dev-tools",
    description: "All-in-one çalışma alanı. Not alma, bilgi tabanı, proje yönetimi ve dokümantasyonu tek bir platformda birleştirir.",
    pricing: "freemium",
    score: 8.6,
    pros: ["Çok yönlü ve esnek yapı", "Veritabanları ve relation desteği", "Şablon ekosistemi zengin", "API ile entegrasyon imkânı"],
    cons: ["Offline desteği sınırlı", "Büyük workspace'lerde performans düşer", "Arama fonksiyonu yetersiz kalabilir"],
    url: "https://www.notion.so/",
    tags: ["documentation", "wiki", "productivity", "workspace"],
  },

  // ─── Database & Data (6) ───
  {
    slug: "postgresql",
    name: "PostgreSQL",
    category: "database",
    description: "En güçlü açık kaynak ilişkisel veritabanı. ACID uyumlu, genişletilebilir ve JSON, GIS gibi ileri düzey veri tiplerini destekler.",
    pricing: "open-source",
    score: 9.5,
    pros: ["ACID tam uyumluluk", "Gelişmiş veri tipleri (JSONB, GIS, array)", "Güçlü sorgu optimizatörü", "Genişletilebilir eklenti sistemi"],
    cons: ["Yatay ölçeklendirme karmaşık", "Varsayılan yapılandırma performans için optimize değil", "Replikasyon kurulumu detaylı bilgi gerektirir"],
    url: "https://www.postgresql.org/",
    tags: ["SQL", "RDBMS", "ACID", "open-source"],
  },
  {
    slug: "mongodb",
    name: "MongoDB",
    category: "database",
    description: "Popüler doküman tabanlı NoSQL veritabanı. Esnek şema yapısı ve yatay ölçeklendirme ile modern uygulamalar için tasarlanmıştır.",
    pricing: "freemium",
    score: 8.3,
    pros: ["Esnek doküman modeli", "Yatay ölçeklendirme (sharding)", "Atlas ile tam yönetilen bulut hizmeti", "Aggregation pipeline güçlü"],
    cons: ["ACID desteği sınırlı (multi-document)", "Bellek tüketimi yüksek", "Lisans değişikliği (SSPL) tartışmalı"],
    url: "https://www.mongodb.com/",
    tags: ["NoSQL", "document-db", "cloud", "flexible-schema"],
  },
  {
    slug: "redis",
    name: "Redis",
    category: "database",
    description: "Bellek içi veri yapı deposu. Cache, message broker, session store ve gerçek zamanlı analitik için kullanılan yüksek performanslı çözüm.",
    pricing: "open-source",
    score: 9.0,
    pros: ["Ultra düşük gecikme süresi", "Zengin veri yapısı desteği", "Pub/Sub ve Stream desteği", "Cluster ile yatay ölçeklendirme"],
    cons: ["RAM maliyeti yüksek", "Veri kalıcılığı yapılandırma gerektirir", "Lisans değişikliği (RSALv2) tartışmalı"],
    url: "https://redis.io/",
    tags: ["cache", "in-memory", "key-value", "real-time"],
  },
  {
    slug: "apache-kafka",
    name: "Apache Kafka",
    category: "database",
    description: "Dağıtık olay akışı platformu. Yüksek verimli mesaj kuyruğu, olay kaynağı ve gerçek zamanlı veri pipeline'ları için kullanılır.",
    pricing: "open-source",
    score: 8.8,
    pros: ["Çok yüksek throughput", "Kalıcı mesaj saklama", "Yatay ölçeklendirme", "Confluent ekosistemi zengin"],
    cons: ["Operasyonel karmaşıklık yüksek", "ZooKeeper bağımlılığı (KRaft ile azalıyor)", "Küçük projeler için aşırı karmaşık"],
    url: "https://kafka.apache.org/",
    tags: ["streaming", "event-driven", "message-queue", "real-time"],
  },
  {
    slug: "elasticsearch",
    name: "Elasticsearch",
    category: "database",
    description: "Dağıtık arama ve analitik motoru. Full-text arama, log analizi ve gerçek zamanlı veri analizi için kullanılan yüksek performanslı çözüm.",
    pricing: "freemium",
    score: 8.7,
    pros: ["Güçlü full-text arama yetenekleri", "Gerçek zamanlı indeksleme", "RESTful API ile kolay entegrasyon", "Yatay ölçeklendirme"],
    cons: ["Yüksek bellek tüketimi", "Cluster yönetimi uzmanlık gerektirir", "SSPL lisansı açık kaynak sayılmaz"],
    url: "https://www.elastic.co/elasticsearch",
    tags: ["search", "analytics", "full-text", "distributed"],
  },
  {
    slug: "clickhouse",
    name: "ClickHouse",
    category: "database",
    description: "Sütun bazlı analitik veritabanı. Milyarlarca satır üzerinde gerçek zamanlı analitik sorguları saniyeler içinde çalıştırır.",
    pricing: "open-source",
    score: 8.5,
    pros: ["Olağanüstü sorgu performansı", "Verimli veri sıkıştırma", "SQL uyumlu sorgu dili", "Gerçek zamanlı veri ekleme"],
    cons: ["UPDATE/DELETE operasyonları sınırlı", "Transaksiyonel iş yükleri için uygun değil", "Operasyonel karmaşıklık yüksek"],
    url: "https://clickhouse.com/",
    tags: ["OLAP", "analytics", "columnar", "real-time"],
  },

  // ─── Collaboration & Project (5) ───
  {
    slug: "jira",
    name: "Jira",
    category: "collaboration",
    description: "Atlassian'ın proje yönetim platformu. Agile/Scrum board'ları, sprint planlama ve issue tracking ile yazılım projelerini yönetir.",
    pricing: "freemium",
    score: 8.0,
    pros: ["Kapsamlı issue tracking", "Agile/Scrum board desteği", "Güçlü filtreleme ve JQL sorgu dili", "Geniş entegrasyon ekosistemi"],
    cons: ["Arayüz karmaşık ve yavaş", "Küçük takımlar için aşırı özellik", "Fiyatlandırma kullanıcı sayısına göre artar"],
    url: "https://www.atlassian.com/software/jira",
    tags: ["project-management", "agile", "issue-tracking", "Atlassian"],
  },
  {
    slug: "linear",
    name: "Linear",
    category: "collaboration",
    description: "Modern ve hızlı proje yönetim aracı. Minimalist arayüzü ve klavye odaklı tasarımıyla yazılım ekipleri için optimize edilmiştir.",
    pricing: "freemium",
    score: 8.8,
    pros: ["Ultra hızlı arayüz", "Klavye kısayolları ile verimli kullanım", "GitHub/GitLab entegrasyonu güçlü", "Temiz ve modern tasarım"],
    cons: ["Jira kadar özelleştirilebilir değil", "Büyük kurumsal yapılar için sınırlı", "Raporlama yetenekleri gelişiyor"],
    url: "https://linear.app/",
    tags: ["project-management", "issue-tracking", "modern", "fast"],
  },
  {
    slug: "slack",
    name: "Slack",
    category: "collaboration",
    description: "Takım iletişim platformu. Kanal bazlı mesajlaşma, dosya paylaşımı, entegrasyonlar ve huddle ile takım iş birliğini kolaylaştırır.",
    pricing: "freemium",
    score: 8.5,
    pros: ["Kapsamlı uygulama ve bot ekosistemi", "Kanal bazlı organizasyon", "Zengin arama ve arşiv", "Workflow Builder ile otomasyon"],
    cons: ["Mesaj geçmişi ücretsiz planda sınırlı", "Bildirim yorgunluğu yaratabilir", "Fiyatlandırma kullanıcı başına yüksek"],
    url: "https://slack.com/",
    tags: ["messaging", "communication", "integration", "teamwork"],
  },
  {
    slug: "confluence",
    name: "Confluence",
    category: "collaboration",
    description: "Atlassian'ın bilgi yönetim platformu. Takım wiki'leri, teknik dokümantasyon ve proje notlarını merkezi bir yerde toplar.",
    pricing: "freemium",
    score: 7.5,
    pros: ["Jira ile derin entegrasyon", "Şablon zenginliği", "Sayfa hiyerarşisi ile organizasyon", "Makro sistemi ile zengin içerik"],
    cons: ["Editör deneyimi zayıf", "Arama fonksiyonu yetersiz", "Sayfa yükleme süreleri yavaş"],
    url: "https://www.atlassian.com/software/confluence",
    tags: ["wiki", "documentation", "knowledge-base", "Atlassian"],
  },
  {
    slug: "miro",
    name: "Miro",
    category: "collaboration",
    description: "Çevrimiçi beyaz tahta ve görsel iş birliği platformu. Beyin fırtınası, mimari diyagramlar ve retrospektifler için idealdir.",
    pricing: "freemium",
    score: 8.3,
    pros: ["Sonsuz kanvas ve gerçek zamanlı iş birliği", "Zengin şablon kütüphanesi", "Diyagram ve akış şeması araçları", "Video konferans entegrasyonu"],
    cons: ["Ücretsiz planda sınırlı board sayısı", "Büyük board'larda performans düşer", "Öğrenme eğrisi yeni kullanıcılar için var"],
    url: "https://miro.com/",
    tags: ["whiteboard", "collaboration", "diagrams", "brainstorming"],
  },
];

export const blogPosts: BlogPost[] = [
  {
    slug: "yapay-zeka-ile-devops-otomasyonu",
    title: "Yapay Zekâ ile DevOps Otomasyonu: 2026'da Neler Değişiyor?",
    excerpt: "AI destekli CI/CD pipeline'ları, otomatik kod review ve anomali tespiti gibi yenilikler DevOps süreçlerini köklü biçimde dönüştürüyor. Pratik örneklerle AI-driven DevOps yaklaşımını inceliyoruz.",
    category: "ai-ml",
    date: "2026-04-07",
    readTime: "8 dk",
    featured: true,
  },
  {
    slug: "platform-engineering-nedir",
    title: "Platform Engineering Nedir? DevOps'un Evrimini Anlamak",
    excerpt: "Internal Developer Platform kavramı ve self-service altyapı yaklaşımı ile geliştirici deneyimini nasıl iyileştirebileceğinizi keşfedin.",
    category: "cicd",
    date: "2026-04-02",
    readTime: "7 dk",
    featured: true,
  },
  {
    slug: "devsecops-pipeline-tasarimi",
    title: "DevSecOps Pipeline Tasarımı: Güvenliği Sola Kaydırmak",
    excerpt: "Shift-left security yaklaşımıyla CI/CD pipeline'ınıza SAST, DAST, SCA ve secret scanning adımlarını nasıl entegre edeceğinizi adım adım anlatıyoruz.",
    category: "security",
    date: "2026-03-28",
    readTime: "10 dk",
    featured: false,
  },
  {
    slug: "kubernetes-production-checklist",
    title: "Kubernetes Production Checklist: Canlıya Çıkmadan Önce 25 Kontrol",
    excerpt: "Resource limits, network policy, RBAC, monitoring ve disaster recovery dahil production Kubernetes cluster'ınız için kapsamlı kontrol listesi.",
    category: "container",
    date: "2026-03-22",
    readTime: "12 dk",
    featured: true,
  },
  {
    slug: "gitops-vs-geleneksel-cicd",
    title: "GitOps vs Geleneksel CI/CD: Hangisi Sizin İçin Doğru?",
    excerpt: "ArgoCD ve Flux gibi GitOps araçlarını geleneksel CI/CD yaklaşımlarıyla karşılaştırıyor, hangi senaryoda hangisini tercih etmeniz gerektiğini açıklıyoruz.",
    category: "cicd",
    date: "2026-03-15",
    readTime: "9 dk",
    featured: false,
  },
  {
    slug: "observability-driven-development",
    title: "Observability-Driven Development: Kodunuzu Gözlemlenebilir Yazın",
    excerpt: "Structured logging, distributed tracing ve metrik enstrümantasyonu ile baştan gözlemlenebilir sistemler tasarlamanın yollarını keşfedin.",
    category: "monitoring",
    date: "2026-03-10",
    readTime: "8 dk",
    featured: false,
  },
  {
    slug: "terraform-vs-pulumi-karsilastirmasi",
    title: "Terraform vs Pulumi: Hangisini Seçmelisiniz?",
    excerpt: "HCL ve genel amaçlı programlama dilleri arasındaki IaC yaklaşım farkını, ekosistem olgunluğunu ve ekip uyumunu detaylı karşılaştırıyoruz.",
    category: "iac",
    date: "2026-03-05",
    readTime: "10 dk",
    featured: false,
  },
  {
    slug: "container-guvenligi-best-practices",
    title: "Container Güvenliği: Image'dan Runtime'a Best Practices",
    excerpt: "Minimal base image seçimi, multi-stage build, rootless container ve runtime güvenlik politikalarıyla konteyner güvenliğini sağlamlaştırın.",
    category: "security",
    date: "2026-02-27",
    readTime: "9 dk",
    featured: true,
  },
  {
    slug: "sre-kulturu-ve-devops-farklari",
    title: "SRE Kültürü ve DevOps: Farklar, Benzerlikler ve Uyum",
    excerpt: "Site Reliability Engineering ile DevOps arasındaki farkları, SLI/SLO/SLA kavramlarını ve error budget yaklaşımını pratik örneklerle anlatıyoruz.",
    category: "monitoring",
    date: "2026-02-20",
    readTime: "7 dk",
    featured: false,
  },
  {
    slug: "cicd-pipeline-optimizasyonu",
    title: "CI/CD Pipeline Optimizasyonu: Build Sürelerinizi Yarıya İndirin",
    excerpt: "Caching stratejileri, paralel iş çalıştırma, incremental build ve test splitting ile pipeline sürelerinizi dramatik şekilde kısaltın.",
    category: "cicd",
    date: "2026-02-14",
    readTime: "8 dk",
    featured: false,
  },
  {
    slug: "cloud-maliyet-optimizasyonu",
    title: "Cloud Maliyet Optimizasyonu: FinOps Pratikleri ile Tasarruf",
    excerpt: "Reserved instance, spot instance, rightsizing ve tag bazlı maliyet takibi ile bulut harcamalarınızı kontrol altına almayı öğrenin.",
    category: "cloud",
    date: "2026-02-07",
    readTime: "9 dk",
    featured: false,
  },
  {
    slug: "microservices-vs-monolith",
    title: "Microservices vs Monolith: Doğru Mimari Kararını Vermek",
    excerpt: "Monolith-first yaklaşımı, domain-driven decomposition ve microservices geçiş stratejilerini gerçek dünya deneyimleriyle değerlendiriyoruz.",
    category: "container",
    date: "2026-01-30",
    readTime: "11 dk",
    featured: false,
  },
  {
    slug: "api-guvenligi-best-practices",
    title: "API Güvenliği: OAuth, Rate Limiting ve Best Practices",
    excerpt: "JWT yönetimi, API gateway güvenliği, rate limiting stratejileri ve OWASP API Top 10 ile API'lerinizi koruma altına alın.",
    category: "security",
    date: "2026-01-22",
    readTime: "10 dk",
    featured: false,
  },
  {
    slug: "devops-metrikleri-dora-metrics",
    title: "DevOps Metrikleri: DORA Metrics ile Performansınızı Ölçün",
    excerpt: "Deployment frequency, lead time, change failure rate ve MTTR metriklerini nasıl toplayacağınızı ve iyileştireceğinizi anlatıyoruz.",
    category: "cicd",
    date: "2026-01-15",
    readTime: "8 dk",
    featured: false,
  },
  {
    slug: "2026-devops-trend-tahminleri",
    title: "2026 DevOps Trend Tahminleri: Platform Engineering'den AI-Ops'a",
    excerpt: "Platform engineering, AI-driven operations, eBPF güvenliği, WebAssembly ve green computing gibi 2026'nın öne çıkan DevOps trendlerini inceliyoruz.",
    category: "ai-ml",
    date: "2026-01-08",
    readTime: "7 dk",
    featured: false,
  },
];
